name: CRA(Create React App) Build & deploy to AWS S3 / CloudFront invalidate
on: 
  push:                            
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code   
        uses: actions/checkout@master

      - name: Cache node modules   
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: npm install

      - name: Build                   
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
        
      - name: Deploy to S3               
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://the-volunteers.com
            
      - name: CloudFront Invalidate
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3R4UO2IGMU9Q4 \
            --paths / /index.html /service-worker.js /manifest.json /favicon.ico /robots.txt /logo192.png /logo512.png /asset-mainfest.json
